		<nav id="top_nav" class = "twelve columns">
			<ul>
				<li><a href ="http://teams.thenet.ca/persius/thenetprotosite">Home </a></li>
				<li><a href ="http://ray448ray.tumblr.com/">News</a></li>
				<li id="lecture_link"><a href ="http://teams.thenet.ca/persius/thenetprotosite/lecture">Lecture</a> </li>
				<li><a href ="http://teams.thenet.ca/persius/thenetprotosite/assigndiscussion">Discussion</a> </li>
				<li><a href ="http://teams.thenet.ca/persius/">Project</a></li>
				<li><a href ="http://validator.w3.org/check?uri=referer" target="_blank">Validate</a></li>
			</ul>
		</nav>
		<div id="search_bar">
			<form>
				<input class="seven columns" type="text" placeholder="Search"/>
				<input type="submit" value="Submit">
			</form>
		</div>