<header>
<section>
<div class="row">

<div class="two columns" id="headerlogo">

<a href="index.shtml"><img src="images/ed2_Prototype.jpg" alt="A Persius Prototype"></a>

</div>  <!-- /.three.columns -->
<div class="ten columns" id="companyintro">

<h1>Team Persius <span>Consulting on Creative Concepts</span></h1>

</div>  <!-- /.nine.columns -->
</div>  <!-- /.row -->
</section>

<section>
<div class="row">
<div class="ten columns" id="searchbar">
<input type="text">
</div>  <!-- /.ten.columns -->

<div class="two columns" id="searchbutton">
<button type="submit">Search</button>
</div>  <!-- /.one.column -->


</div>  <!-- /.row -->
</section>



</header>

<div class="row">
<div class="twelve columns">
<nav>
	<ul id="mainmenu">
		<li><a href="index.shtml">Home</a></li>
		<li><a href="#">Project</a>
			<ul>
				<li><a href="intro.shtml">Intro</a></li>
				<li><a href="methodology.shtml">Methodology</a></li>
			</ul>
		</li>
		<li><a href="members.shtml">Our Team</a></li>
		<li><a href="artifacts.shtml">Artifacts</a></li>
		<li><a href="../persius/thenetprotosite/index.shtml">Protosite</a></li>
		<li><a href="sitemap.shtml">Sitemap</a></li>
		<li><a href="rationale.shtml">Rationale</a></li>
	</ul>
</nav>
</div>  <!-- /.twelve.columns -->
</div>  <!-- /.row -->

