<header>
<section>
<div class="row">

<div class="two columns" id="headerlogo">

<img src="http://www.mbtmag.com/sites/mbtmag.com/files/legacyimages/1109/12/ed2_Prototype.jpg" alt="A Persius Prototype">

</div>  <!-- /.three.columns -->
<div class="ten columns" id="companyintro">

<h1>Team Persius <span>Consulting on Creative Concepts</span></h1>

</div>  <!-- /.nine.columns -->
</div>  <!-- /.row -->
</section>

<section>
<div class="row">
<div class="ten columns" id="searchbar">
<input type="text">
</div>  <!-- /.ten.columns -->

<div class="two columns" id="searchbutton">
<button type="submit">Search</button>
</div>  <!-- /.one.column -->


</div>  <!-- /.row -->
</section>



</header>

<div class="row">
<div class="twelve columns">
<nav>
	<ul id="mainmenu">
		<li><a href="index.shtml">Home</a>
			<ul>
				<li><a href="intro.shtml">Intro</a></li>
				<li><a href="methodology.shtml">Methodology</a></li>
			</ul>
		</li>
		<li><a href="#">Our Team</a>
			<ul>
				<li><a href="members.shtml">Members</a></li>
				<li><a href="responsibilities.shtml">Responsibilities</a></li>
			</ul>
		</li>
		<li><a href="artifacts.shtml">Artifacts</a></li>
		<li><a href="protosite.shtml">Protosite</a>
			<ul>
				<li><a href="../persius/thenetprotosite/index.html">thenet.ca redesigned</a></li>
				<li><a href="#">Page 2</a></li>
				<li><a href="#">Page 3</a></li>
				<li><a href="#">Page 4</a></li>
			</ul>
		</li>
		<li><a href="sitemap.shtml">Sitemap</a></li>
		<li><a href="rationale.shtml">Rationale</a></li>
	</ul>
</nav>
</div>  <!-- /.twelve.columns -->
</div>  <!-- /.row -->

