$(document).ready(function(){
	$("ul.sublist").hide();
	$("a#lecture1").click(function(){
		$("#sublist1").slideToggle();
	});
	$("a#lecture2").click(function(){
		$("#sublist2").slideToggle();
	});
	$("a#lecture3").click(function(){
		$("#sublist3").slideToggle();
	});
	$("a#lecture4").click(function(){
		$("#sublist4").slideToggle();
	});
	$("a#lecture5").click(function(){
		$("#sublist5").slideToggle();
	});
	$("a#lecture6").click(function(){
		$("#sublist6").slideToggle();
	});
	$("a#lecture7").click(function(){
		$("#sublist7").slideToggle();
	})
	;$("a#lecture8").click(function(){
		$("#sublist8").slideToggle();
	});
	$("a#lecture9").click(function(){
		$("#sublist9").slideToggle();
	});
	$("a#lecture10").click(function(){
		$("#sublist10").slideToggle();
	});
	$("a#lecture11").click(function(){
		$("#sublist11").slideToggle();
	});
	$("a#lecture12").click(function(){
		$("#sublist12").slideToggle();
	});
});