		<nav id="top_nav" class = "twelve columns">
			<ul>
				<li><a href ="http://teams.thenet.ca/persius/thenetprotosite">Home </a></li>
				<li><a href ="#">News</a></li>
				<li><a href ="http://teams.thenet.ca/persius/thenetprotosite/lecture">Lecture</a> </li>
				<li><a href ="#">Project</a></li>
				<li><a href ="#">Discussion</a> </li>
				<li><a href ="#">Instructor Feedback</a> </li>
			</ul>
		</nav>
		<div id="search_bar">
			<form>
				<input class="seven columns" type="text" placeholder="Search"/>
				<input type="submit" value="Submit">
			</form>
		</div>