			<div id="left_nav" class = "two columns">
			<ul>
				<li><a href ="#" id="lecture1">Lecture 1</a></li>
				<ul class="sublist" id="sublist1">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture2">Lecture 2</a></li>
				<ul class="sublist" id="sublist2">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture3">Lecture 3</a></li>
				<ul class="sublist" id="sublist3">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture4">Lecture 4</a></li>
				<ul class="sublist" id="sublist4">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture5">Lecture 5</a></li>
				<ul class="sublist" id="sublist5">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture6">Lecture 6</a></li>
				<ul class="sublist" id="sublist6">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture7">Lecture 7</a></li>
				<ul class="sublist" id="sublist7">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture8">Lecture 8</a></li>
				<ul class="sublist" id="sublist8">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture9">Lecture 9</a></li>
				<ul class="sublist" id="sublist9">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture10">Lecture 10</a></li>
				<ul class="sublist" id="sublist10">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture11">Lecture 11</a></li>
				<ul class="sublist" id="sublist11">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture12">Lecture 12</a></li>
				<ul class="sublist" id="sublist12">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
			</ul>
			</div>