			<div id="left_nav" class = "two columns">
			<ul>
				<li><a href ="#" id="lecture1">Lecture 1</a>
				<ul class="sublist" id="sublist1">
					<li><a href ="http://teams.thenet.ca/persius/thenetprotosite/lecture/1#web-review">Web Review</a></li>
					<li><a href ="http://teams.thenet.ca/persius/thenetprotosite/lecture/1#homework-review">HW Review</a></li>
					<li><a href ="http://teams.thenet.ca/persius/thenetprotosite/lecture/1#browser-tools">Tools</a></li>
					<li><a href ="http://teams.thenet.ca/persius/thenetprotosite/lecture/1#homework">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture2">Lecture 2</a>
				<ul class="sublist" id="sublist2">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture3">Lecture 3</a>
				<ul class="sublist" id="sublist3">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture4">Lecture 4</a>
				<ul class="sublist" id="sublist4">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture5">Lecture 5</a>
				<ul class="sublist" id="sublist5">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture6">Lecture 6</a>
				<ul class="sublist" id="sublist6">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture7">Lecture 7</a>
				<ul class="sublist" id="sublist7">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture8">Lecture 8</a>
				<ul class="sublist" id="sublist8">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture9">Lecture 9</a>
				<ul class="sublist" id="sublist9">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture10">Lecture 10</a>
				<ul class="sublist" id="sublist10">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				<li><a href ="#" id="lecture11">Lecture 11</a>
				<ul class="sublist" id="sublist11">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
				<li><a href ="#" id="lecture12">Lecture 12</a>
				<ul class="sublist" id="sublist12">
					<li><a href ="#">Topic 1</a></li>
					<li><a href ="#">Topic 2</a></li>
					<li><a href ="#">Homework</a></li>
				</ul>
				</li>
			</ul>
			</div>